const translations = {
  km: {
    languageName: 'ខ្មែរ', meta: { title: 'មតិយោបល់ភ្ញៀវ | MACHIDA SHOTEN Khalandale Mall' },
    landing: { title: 'សូមប្រាប់យើងអំពីការមកទទួលទានរបស់អ្នក', subtitle: 'មតិយោបល់របស់អ្នកជួយឱ្យយើងបម្រើអ្នកបានកាន់តែប្រសើរ។' },
    visit: { partySize: 'ចំនួនអ្នកមកជាមួយ', visitCount: 'ចំនួនដងមកទទួលទានក្នុងមួយខែ', diningWith: 'អ្នកមកទទួលទានជាមួយអ្នកណា?', ageGroup: 'ក្រុមអាយុ', gender: 'ភេទ' },
    option: {
      party: { '1': '១ នាក់', '2': '២ នាក់', '3-4': '៣–៤ នាក់', '5-8': '៥–៨ នាក់', '9-plus': '៩+ នាក់' },
      visit: { first: 'មកលើកដំបូង', '2-3': '២–៣ ដង', '4-10': '៤–១០ ដង', '11-plus': '១១ ដងឡើងទៅ' },
      dining: { solo: 'ម្នាក់ឯង', couple: 'គូស្នេហ៍', family: 'គ្រួសារ', friends: 'មិត្តភក្តិ', business: 'ការងារ' },
      age: { 'under-20': 'ក្រោម ២០', '20s': 'អាយុ ២០', '30s': 'អាយុ ៣០', '40s': 'អាយុ ៤០', '50s': 'អាយុ ៥០', '60-plus': '៦០ ឡើងទៅ', 'prefer-not-say': 'មិនចង់ប្រាប់' },
      gender: { male: 'ប្រុស', female: 'ស្រី', other: 'ផ្សេងទៀត', 'prefer-not-say': 'មិនចង់ប្រាប់' },
      meal: { breakfast: 'អាហារពេលព្រឹក', brunch: 'ប្រាន់ជ៍', lunch: 'អាហារថ្ងៃត្រង់', dinner: 'អាហារពេលល្ងាច', other: 'ផ្សេងទៀត' },
      spend: { '1-5': '$១–៥', '5-10': '$៥–១០', '10-15': '$១០–១៥', '15-20': '$១៥–២០', '20-25': '$២០–២៥', '25-30': '$២៥–៣០', '30-35': '$៣០–៣៥', '35-40': '$៣៥–៤០', '40-45': '$៤០–៤៥', '45-50': '$៤៥–៥០', '50-plus': '$៥០+' },
      group: { '1': '១ នាក់', '2': '២ នាក់', '3-4': '៣–៤ នាក់', '5-8': '៥–៨ នាក់', '9-plus': '៩+ នាក់', all: 'គ្រប់ទំហំក្រុម', 'not-sure': 'មិនប្រាកដ' },
      noise: { quiet: 'ស្ងាត់ណាស់', easy: 'ស្ងាត់ ងាយនិយាយ', moderate: 'សំឡេងមធ្យម', loud: 'ខ្លាំង ប៉ុន្តែនៅអាចនិយាយបាន', veryLoud: 'ខ្លាំងណាស់ ពិបាកស្តាប់', 'not-sure': 'មិនប្រាកដ' }
    },
    review: { eyebrow: 'បទពិសោធន៍របស់អ្នក', private: 'មតិយោបល់នេះនឹងផ្ញើជាសម្ងាត់ទៅ MACHIDA SHOTEN', overall: 'ការវាយតម្លៃសរុបរបស់អ្នក', overallQuestion: 'តើបទពិសោធន៍របស់អ្នកជារួមយ៉ាងដូចម្តេច?', title: 'ចែករំលែកមតិយោបល់របស់អ្នក', food: 'ម្ហូបអាហារ', service: 'សេវាកម្ម', atmosphere: 'បរិយាកាស', commentLabel: 'ប្រាប់យើងអំពីបទពិសោធន៍របស់អ្នកនៅភោជនីយដ្ឋាននេះ', commentPlaceholder: 'ចែករំលែកគំនិតរបស់អ្នក', addPhotos: 'បន្ថែមរូបថត និងវីដេអូ', whatDidYouGet: 'តើអ្នកបានទទួលទានអ្វី?', spending: 'តើអ្នកចំណាយប៉ុន្មានក្នុងម្នាក់?', groupSuitability: 'កន្លែងនេះសមស្របសម្រាប់ក្រុមទំហំប៉ុន្មាន?', selectAll: 'ជ្រើសរើសបានច្រើន', noiseLevel: 'តើអ្នកពិពណ៌នាកម្រិតសំឡេងយ៉ាងដូចម្តេច?', addDetails: 'បន្ថែមព័ត៌មានដើម្បីជួយអ្នកដទៃ' },
    accordion: { vegetarian: 'ជម្រើសបួស', vegetarianHelper: 'ប្រាប់យើងអំពីជម្រើសដែលមាន', vegetarianPlaceholder: 'ប្រាប់យើងអំពីជម្រើសម្ហូបបួស', dietary: 'កម្រិតអាហារ', dietaryHelper: 'ប្រាប់យើងអំពីការគាំទ្រដែលមាន', dietaryPlaceholder: 'ប្រាប់យើងអំពីការគាំទ្រសម្រាប់កម្រិតអាហារ', parking: 'ចំណតរថយន្ត', parkingHelper: 'ប្រាប់យើងថាងាយស្រួលប៉ុណ្ណា', parkingQuestion: 'តើការស្វែងរកចំណតងាយស្រួលប៉ុណ្ណា?', parkingOptions: 'តើមានជម្រើសចំណតអ្វីខ្លះ?', otherDetails: 'ព័ត៌មានផ្សេងទៀត', parkingPlaceholder: 'ទីតាំង ចំនួនកន្លែងចត និងព័ត៌មានផ្សេងៗ', kids: 'ភាពសមស្របសម្រាប់កុមារ', kidsHelper: 'ប្រាប់យើងអំពីបទពិសោធន៍របស់អ្នក', kidsPlaceholder: 'ប្រាប់យើងថាកន្លែងនេះសមស្របសម្រាប់កុមារប៉ុណ្ណា', wheelchair: 'ភាពងាយស្រួលសម្រាប់រទេះរុញ', wheelchairHelper: 'ប្រាប់យើងអំពីការចូលប្រើ', wheelchairMore: 'ប្រាប់យើងបន្ថែមអំពីភាពងាយស្រួល', wheelchairPlaceholder: 'ប្រាប់យើងបន្ថែមអំពីភាពងាយស្រួល' },
    parking: { plenty: 'មានចំណតគ្រប់គ្រាន់', somewhat: 'ពិបាករកបន្តិច', difficult: 'ពិបាករកណាស់', freeLot: 'ចំណតឥតគិតថ្លៃ', paidLot: 'ចំណតមានគិតថ្លៃ', freeStreet: 'ចតតាមផ្លូវឥតគិតថ្លៃ', paidStreet: 'ចតតាមផ្លូវមានគិតថ្លៃ', valet: 'ចំណតដោយបុគ្គលិក', freeGarage: 'អគារចតឥតគិតថ្លៃ', paidGarage: 'អគារចតមានគិតថ្លៃ', unavailable: 'គ្មានចំណត' },
    accessibility: { entrance: 'ច្រកចូលសមស្របសម្រាប់រទេះរុញ', restroom: 'បន្ទប់ទឹកសមស្របសម្រាប់រទេះរុញ', seating: 'កន្លែងអង្គុយសមស្របសម្រាប់រទេះរុញ', parking: 'ចំណតសមស្របសម្រាប់រទេះរុញ', elevator: 'ជណ្តើរយន្តសមស្របសម្រាប់រទេះរុញ', notSure: 'មិនប្រាកដ' },
    action: { next: 'បន្ទាប់', cancel: 'បោះបង់', post: 'ផ្ញើ', back: 'ត្រឡប់', sending: 'កំពុងផ្ញើ…', sent: 'បានផ្ញើ', retry: 'ផ្ញើមិនបាន។ សូមព្យាយាមម្តងទៀត។', selectRating: 'ជ្រើសរើសការវាយតម្លៃ', star: 'ផ្កាយ' },
    complete: { eyebrow: 'បានទទួលមតិយោបល់', title: 'អរគុណសម្រាប់មតិយោបល់របស់អ្នក', message: 'មតិយោបល់របស់អ្នកនឹងត្រូវចែករំលែកជាមួយក្រុមការងាររបស់យើង។' },
    errors: { maxPhotos: 'អ្នកអាចបន្ថែមរូបថតបានរហូតដល់ {count}។', imagesOnly: '{name}: សូមជ្រើសរើសតែឯកសាររូបភាព។', maxSize: '{name}: ទំហំអតិបរមាគឺ ១០ MB។', duplicate: '{name}: បានបន្ថែមរួចហើយ។', remove: 'លុប {name}', photoCount: '{count} / {max} រូបថតបានជ្រើសរើស' }
  },
  en: {
    languageName: 'English', meta: { title: 'Guest feedback | MACHIDA SHOTEN Khalandale Mall' },
    landing: { title: 'Tell us about your visit', subtitle: 'Your feedback helps us serve you better.' },
    visit: { partySize: 'Party size', visitCount: 'How many times do you visit per month?', diningWith: 'Who are you dining with?', ageGroup: 'Age group', gender: 'Gender' },
    option: { party: { '1': '1 person', '2': '2 people', '3-4': '3–4 people', '5-8': '5–8 people', '9-plus': '9+ people' }, visit: { first: 'First time', '2-3': '2–3 times', '4-10': '4–10 times', '11-plus': '11+ times' }, dining: { solo: 'Solo', couple: 'Couple', family: 'Family', friends: 'Friends', business: 'Business' }, age: { 'under-20': 'Under 20', '20s': '20s', '30s': '30s', '40s': '40s', '50s': '50s', '60-plus': '60+', 'prefer-not-say': 'Prefer not to say' }, gender: { male: 'Male', female: 'Female', other: 'Other', 'prefer-not-say': 'Prefer not to say' }, meal: { breakfast: 'Breakfast', brunch: 'Brunch', lunch: 'Lunch', dinner: 'Dinner', other: 'Other' }, spend: { '1-5': '$1–5', '5-10': '$5–10', '10-15': '$10–15', '15-20': '$15–20', '20-25': '$20–25', '25-30': '$25–30', '30-35': '$30–35', '35-40': '$35–40', '40-45': '$40–45', '45-50': '$45–50', '50-plus': '$50+' }, group: { '1': '1 person', '2': '2 people', '3-4': '3–4 people', '5-8': '5–8 people', '9-plus': '9+ people', all: 'Suitable for all group sizes', 'not-sure': 'Not sure' }, noise: { quiet: 'Very quiet', easy: 'Quiet, easy to talk', moderate: 'Moderate noise', loud: 'Loud, but you can still talk', veryLoud: 'Very loud, hard to hear', 'not-sure': 'Not sure' } },
    review: { eyebrow: 'YOUR EXPERIENCE', private: 'Feedback sent privately to MACHIDA SHOTEN', overall: 'Your overall rating', overallQuestion: 'How was your overall experience?', title: 'Share your feedback', food: 'Food', service: 'Service', atmosphere: 'Atmosphere', commentLabel: 'Tell us about your experience at this restaurant', commentPlaceholder: 'Share your thoughts', addPhotos: 'Add photos and videos', whatDidYouGet: 'What did you get?', spending: 'How much did you spend per person?', groupSuitability: 'What size group is this place best suited for?', selectAll: 'Select all that apply', noiseLevel: 'How would you describe the noise level?', addDetails: 'Add more details to help others' },
    accordion: { vegetarian: 'Vegetarian options', vegetarianHelper: 'Tell us about the options available', vegetarianPlaceholder: 'Tell us about the vegetarian options available', dietary: 'Dietary restrictions', dietaryHelper: 'Tell us about the support available', dietaryPlaceholder: 'Tell us about support for dietary restrictions', parking: 'Parking', parkingHelper: 'Tell us how convenient it was', parkingQuestion: 'How easy was it to find parking?', parkingOptions: 'What parking options are available?', otherDetails: 'Other details', parkingPlaceholder: 'Location, number of parking spaces, etc.', kids: 'Kid-friendliness', kidsHelper: 'Tell us about your experience', kidsPlaceholder: 'Tell us about how suitable this place is for children', wheelchair: 'Wheelchair accessibility', wheelchairHelper: 'Tell us about the access', wheelchairMore: 'Tell us more about the accessibility', wheelchairPlaceholder: 'Tell us more about the accessibility' },
    parking: { plenty: 'Plenty of parking', somewhat: 'Parking was somewhat difficult to find', difficult: 'Parking was difficult to find', freeLot: 'Free parking lot', paidLot: 'Paid parking lot', freeStreet: 'Free street parking', paidStreet: 'Paid street parking', valet: 'Valet parking', freeGarage: 'Free parking garage', paidGarage: 'Paid parking garage', unavailable: 'Parking unavailable' },
    accessibility: { entrance: 'Wheelchair-accessible entrance', restroom: 'Wheelchair-accessible restroom', seating: 'Wheelchair-accessible seating', parking: 'Wheelchair-accessible parking', elevator: 'Wheelchair-accessible elevator', notSure: 'Not sure' },
    action: { next: 'Next', cancel: 'Cancel', post: 'Post', back: 'Back', sending: 'Sending…', sent: 'Sent', retry: 'Could not send. Please try again.', selectRating: 'Select a rating', star: 'star' },
    complete: { eyebrow: 'MESSAGE RECEIVED', title: 'Thank you for your feedback', message: 'Your comments will be shared with our team.' },
    errors: { maxPhotos: 'You can add up to {count} photos.', imagesOnly: '{name}: image files only.', maxSize: '{name}: maximum size is 10 MB.', duplicate: '{name}: already added.', remove: 'Remove {name}', photoCount: '{count} / {max} photos selected' }
  },
  'zh-CN': {
    languageName: '简体中文', meta: { title: '顾客反馈 | MACHIDA SHOTEN Khalandale Mall' },
    landing: { title: '请告诉我们您的用餐体验', subtitle: '您的反馈将帮助我们提供更好的服务。' },
    visit: { partySize: '用餐人数', visitCount: '您每月来店多少次？', diningWith: '您和谁一起用餐？', ageGroup: '年龄段', gender: '性别' },
    option: { party: { '1': '1人', '2': '2人', '3-4': '3–4人', '5-8': '5–8人', '9-plus': '9人以上' }, visit: { first: '第一次', '2-3': '2–3次', '4-10': '4–10次', '11-plus': '11次以上' }, dining: { solo: '独自一人', couple: '情侣', family: '家人', friends: '朋友', business: '商务' }, age: { 'under-20': '20岁以下', '20s': '20多岁', '30s': '30多岁', '40s': '40多岁', '50s': '50多岁', '60-plus': '60岁以上', 'prefer-not-say': '不愿透露' }, gender: { male: '男', female: '女', other: '其他', 'prefer-not-say': '不愿透露' }, meal: { breakfast: '早餐', brunch: '早午餐', lunch: '午餐', dinner: '晚餐', other: '其他' }, spend: { '1-5': '$1–5', '5-10': '$5–10', '10-15': '$10–15', '15-20': '$15–20', '20-25': '$20–25', '25-30': '$25–30', '30-35': '$30–35', '35-40': '$35–40', '40-45': '$40–45', '45-50': '$45–50', '50-plus': '$50+' }, group: { '1': '1人', '2': '2人', '3-4': '3–4人', '5-8': '5–8人', '9-plus': '9人以上', all: '适合所有人数', 'not-sure': '不确定' }, noise: { quiet: '非常安静', easy: '安静，方便交谈', moderate: '中等音量', loud: '声音较大，但仍可交谈', veryLoud: '非常吵，难以听清', 'not-sure': '不确定' } },
    review: { eyebrow: '您的体验', private: '您的反馈将私下发送给 MACHIDA SHOTEN', overall: '您的总体评分', overallQuestion: '您的总体体验如何？', title: '分享您的反馈', food: '食物', service: '服务', atmosphere: '氛围', commentLabel: '告诉我们您在这家餐厅的体验', commentPlaceholder: '分享您的想法', addPhotos: '添加照片和视频', whatDidYouGet: '您吃了什么？', spending: '您每人消费了多少？', groupSuitability: '这家餐厅最适合多大规模的团体？', selectAll: '可多选', noiseLevel: '您如何评价这里的噪音？', addDetails: '添加更多信息，帮助其他顾客' },
    accordion: { vegetarian: '素食选择', vegetarianHelper: '告诉我们有哪些选择', vegetarianPlaceholder: '告诉我们这里提供的素食选择', dietary: '饮食限制', dietaryHelper: '告诉我们可提供哪些支持', dietaryPlaceholder: '告诉我们对饮食限制的支持', parking: '停车', parkingHelper: '告诉我们停车是否方便', parkingQuestion: '寻找停车位容易吗？', parkingOptions: '这里有哪些停车选择？', otherDetails: '其他信息', parkingPlaceholder: '位置、停车位数量等', kids: '适合儿童', kidsHelper: '告诉我们您的体验', kidsPlaceholder: '告诉我们这里对儿童是否友好', wheelchair: '无障碍设施', wheelchairHelper: '告诉我们无障碍情况', wheelchairMore: '告诉我们更多无障碍信息', wheelchairPlaceholder: '告诉我们更多无障碍信息' },
    parking: { plenty: '停车位充足', somewhat: '停车位较难寻找', difficult: '停车位很难寻找', freeLot: '免费停车场', paidLot: '收费停车场', freeStreet: '免费路边停车', paidStreet: '收费路边停车', valet: '代客泊车', freeGarage: '免费停车楼', paidGarage: '收费停车楼', unavailable: '无法停车' },
    accessibility: { entrance: '无障碍入口', restroom: '无障碍卫生间', seating: '无障碍座位', parking: '无障碍停车位', elevator: '无障碍电梯', notSure: '不确定' },
    action: { next: '下一步', cancel: '取消', post: '提交', back: '返回', sending: '正在提交…', sent: '已提交', retry: '提交失败，请重试。', selectRating: '请选择评分', star: '星' },
    complete: { eyebrow: '已收到反馈', title: '感谢您的反馈', message: '您的意见将与我们的团队分享。' },
    errors: { maxPhotos: '最多可添加 {count} 张照片。', imagesOnly: '{name}：只能选择图片文件。', maxSize: '{name}：文件大小不能超过10 MB。', duplicate: '{name}：已经添加。', remove: '删除{name}', photoCount: '已选择 {count} / {max} 张照片' }
  }
};
translations.km.errors.completeQuestions = 'សូមឆ្លើយសំណួរទាំងអស់មុនពេលបន្ត។';
translations.en.errors.completeQuestions = 'Please answer all questions before continuing.';
translations['zh-CN'].errors.completeQuestions = '请回答所有问题后再继续。';

function translationValue(locale, key) {
  return key.split('.').reduce((value, part) => value?.[part], translations[locale]) ?? key;
}
